-- 1. User Info
create table if not exists user_info
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp with time zone default now() not null,
    updated_at    timestamp with time zone default now() not null,
    user_id       varchar,
    name          varchar,
    email         varchar,
    image         varchar,
    last_login_ip varchar
);
comment on table user_info is 'user info table';
comment on column user_info.user_id is 'user uuid';

-- 2. User Available (Credits)
create table if not exists user_available
(
    id                 bigint generated by default as identity primary key,
    created_at         timestamp with time zone default now() not null,
    updated_at         timestamp with time zone default now() not null,
    user_id            varchar,
    stripe_customer_id varchar,
    available_times    integer
);
comment on table user_available is 'User credits/quota table';

-- 3. Stripe Customers
create table if not exists stripe_customers
(
    user_id            varchar not null primary key,
    stripe_customer_id text
);
comment on table stripe_customers is 'stripe customers mapping';

-- 4. Stripe Subscriptions
do $$ begin
    create type subscription_status as enum ('trialing', 'active', 'canceled', 'incomplete', 'incomplete_expired', 'past_due', 'unpaid', 'paused');
exception
    when duplicate_object then null;
end $$;

create table if not exists stripe_subscriptions
(
    id                   text not null primary key,
    user_id              varchar,
    status               subscription_status,
    metadata             jsonb,
    price_id             text,
    quantity             integer,
    cancel_at_period_end boolean,
    created              timestamp with time zone default timezone('utc'::text, now()) not null,
    current_period_start timestamp with time zone default timezone('utc'::text, now()) not null,
    current_period_end   timestamp with time zone default timezone('utc'::text, now()) not null,
    ended_at             timestamp with time zone default timezone('utc'::text, now()),
    cancel_at            timestamp with time zone default timezone('utc'::text, now()),
    canceled_at          timestamp with time zone default timezone('utc'::text, now()),
    trial_start          timestamp with time zone default timezone('utc'::text, now()),
    trial_end            timestamp with time zone default timezone('utc'::text, now())
);
comment on table stripe_subscriptions is 'subscriptions';

-- 5. Works (Generated Content/Stickers)
create table if not exists works
(
    id               bigint generated by default as identity primary key,
    created_at       timestamp with time zone default now() not null,
    updated_at       timestamp with time zone default now() not null,
    uid              varchar,
    input_text       varchar,
    revised_text     varchar,
    output_url       varchar,
    is_public        boolean default false,
    status           integer,
    user_id          varchar,
    is_origin        boolean,
    origin_language  varchar,
    current_language varchar,
    is_delete        boolean default false
);
comment on table works is 'Generated works/stickers';

-- 6. Key Value Store
create table if not exists key_value
(
    key   varchar not null constraint key_value_pk primary key,
    value varchar
);

-- 7. Search Log
create table if not exists search_log
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone default now() not null,
    search_text  varchar,
    result_count varchar,
    user_agent   varchar,
    search_ip    varchar
);

-- 8. Sensitive Words
create table if not exists sensitive_words
(
    id    bigint generated by default as identity primary key,
    words varchar,
    level varchar
);

-- 9. Color Lab Waitlist
create table if not exists color_lab_waitlist
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone default now() not null,
    email        varchar not null,
    locale       varchar,
    interest     varchar,
    price_range  varchar
);
comment on table color_lab_waitlist is 'Waitlist for AI color analysis';

-- 10. Color Lab Sessions
create table if not exists color_lab_sessions
(
    id          uuid primary key,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    email       varchar,
    status      varchar not null default 'created',
    ip          varchar
);
comment on table color_lab_sessions is 'AI color analysis sessions';
create index if not exists idx_color_lab_sessions_ip on color_lab_sessions(ip);

-- 11. Color Lab Images
create table if not exists color_lab_images
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp with time zone default now() not null,
    session_id  uuid    not null references color_lab_sessions (id) on delete cascade,
    url         varchar not null,
    image_type  varchar
);
comment on table color_lab_images is 'Uploaded images for color analysis';

-- 12. Color Lab Reports
create table if not exists color_lab_reports
(
    session_id  uuid primary key references color_lab_sessions (id) on delete cascade,
    created_at  timestamp with time zone default now() not null,
    season      varchar,
    payload     jsonb   not null,
    is_featured boolean default false
);
comment on table color_lab_reports is 'Stored JSON reports for color analysis';
create index if not exists idx_color_lab_reports_featured on color_lab_reports(is_featured);

-- 13. Credit Logs
create table if not exists credit_logs
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone default now() not null,
    user_id      varchar not null,
    amount       integer not null,
    type         varchar not null,
    description  varchar
);
comment on table credit_logs is 'Transaction logs for user credits';
create index if not exists idx_credit_logs_user_id on credit_logs(user_id);
-- Feedback columns
ALTER TABLE color_lab_reports ADD COLUMN IF NOT EXISTS rating varchar(10);
ALTER TABLE color_lab_reports ADD COLUMN IF NOT EXISTS feedback_comment text;

