create table if not exists color_lab_sessions
(
    id          uuid primary key,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    email       varchar,
    status      varchar not null default 'created',
    ip          varchar(45)
);

create index if not exists idx_color_lab_sessions_ip on color_lab_sessions(ip);

comment on table color_lab_sessions is 'AI color analysis sessions';
comment on column color_lab_sessions.status is 'created | analyzing | analyzed';

create table if not exists color_lab_images
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp with time zone default now() not null,
    session_id  uuid    not null references color_lab_sessions (id) on delete cascade,
    url         varchar not null,
    image_type  varchar
);

comment on table color_lab_images is 'uploaded and generated images';

create table if not exists color_lab_reports
(
    session_id  uuid primary key references color_lab_sessions (id) on delete cascade,
    created_at  timestamp with time zone default now() not null,
    season      varchar,
    payload     jsonb   not null
);

comment on table color_lab_reports is 'stored JSON reports from Gemini';

create table if not exists color_lab_waitlist
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp with time zone default now() not null,
    email       varchar unique not null,
    locale      varchar,
    interest    varchar,
    price_range varchar
);
