-- waitlist for AI color analysis early access

create table if not exists color_lab_waitlist
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp with time zone default now() not null,
    email        varchar                                not null,
    locale       varchar,
    interest     varchar,
    price_range  varchar
);

comment on table color_lab_waitlist is 'email waitlist for color lab early access';
comment on column color_lab_waitlist.email is 'user email';
comment on column color_lab_waitlist.interest is 'wardrobe | makeup | hair | all';
comment on column color_lab_waitlist.price_range is 'user expected price band';

