-- tables for AI color analysis MVP

create table if not exists color_lab_sessions
(
    id          uuid primary key,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null,
    email       varchar,
    status      varchar not null default 'created'
);

comment on table color_lab_sessions is 'AI color analysis sessions';
comment on column color_lab_sessions.id is 'session uuid';
comment on column color_lab_sessions.status is 'created | paid | analyzed';

create table if not exists color_lab_images
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp with time zone default now() not null,
    session_id  uuid    not null references color_lab_sessions (id) on delete cascade,
    url         varchar not null,
    image_type  varchar
);

comment on table color_lab_images is 'uploaded images for color analysis';

create table if not exists color_lab_reports
(
    session_id  uuid primary key references color_lab_sessions (id) on delete cascade,
    created_at  timestamp with time zone default now() not null,
    season      varchar,
    payload     jsonb   not null
);

comment on table color_lab_reports is 'stored JSON reports for color analysis';
