-- auto-generated definition based on usage
create table if not exists credit_logs
(
    id          bigint generated by default as identity primary key,
    created_at  timestamp with time zone default now() not null,
    user_id     varchar not null,
    amount      integer not null,
    type        varchar not null, -- 'purchase' | 'usage' | 'bonus'
    description varchar
);

comment on table credit_logs is 'log of all credit transactions (additions and deductions)';
comment on column credit_logs.user_id is 'user uuid from user_info';
comment on column credit_logs.amount is 'positive for add, negative for usage';
comment on column credit_logs.type is 'transaction type';
