import { getColorLabText } from '~/i18n/languageText';
import { getColorLabReport } from '~/servers/colorLab';
import PageComponent from '../../report/[id]/PageComponent'; // Reuse existing component
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { EXAMPLE_MAP } from '~/libs/examples';

// Mapping Slug -> UUID moved to src/libs/examples.ts

// SEO Metadata Generator
export async function generateMetadata({ params: { slug } }: { params: { slug: string } }): Promise<Metadata> {
  const prettyName = slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  return {
    title: `${prettyName} | Real AI Color Analysis Results`,
    description: `See a real example of a ${prettyName} report. Discover the palette, makeup, and styling guide generated by our AI.`,
    alternates: {
        canonical: `/examples/${slug}`
    }
  }
}

// Static Params for SSG (SEO Boost)
export async function generateStaticParams() {
  return Object.keys(EXAMPLE_MAP).map((slug) => ({ slug }));
}

export default async function ExamplePage({
  params: { locale, slug }
}: {
  params: { locale: string; slug: string }
}) {
  const uuid = EXAMPLE_MAP[slug];
  if (!uuid) return notFound();

  const colorLabText = await getColorLabText();
  const data = await getColorLabReport(uuid);

  if (!data) {
      return <div>Example not found</div>
  }

  // Force isOwner=false so it looks like a public view (no feedback buttons, etc.)
  // Force status='completed' just in case
  const reportData = {
      ...data,
      status: 'completed'
  };

  return (
    <PageComponent 
        locale={locale} 
        report={reportData.report} 
        status={'completed'} 
        userImage={reportData.imageUrl}
        drapingImages={reportData.drapingImages}
        colorLabText={colorLabText} 
        sessionId={uuid} // Use UUID as session ID for logic, but isOwner is false
        rating={data.rating}
        isOwner={false} 
    />
  )
}
